import MultiNeuron.Network.Core
import MultiNeuron.Network.CoreTest
import MultiNeuron.Relaxation.Crosslayer
import MultiNeuron.Relaxation.Layerwise
import MultiNeuron.Relaxation.LayerwiseTest
import MultiNeuron.Results.«Lemma3-1»
import MultiNeuron.Results.«Lemma3-2»
import MultiNeuron.Results.«Lemma4-1»
import MultiNeuron.Results.«Theorem3-3»
import MultiNeuron.Results.«Theorem4-2»
